--- #YAML:1.0
name:               Fliggy
version:            0.009002
abstract:           Fliggy is Twiggy with inlined flash policy server
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    perl:    5.008007
    Twiggy:  0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/vti/fliggy
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
